### ISSUE TITLE
Possible to disable resolution, and just use whatever value I give?

### ISSUE THREAD

**Issue by callumlocke** [Velenir/babel-plugin-import-redirect#2]
Thanks for writing this plugin.

Is it possible to prevent it trying to resolve things through the filesystem, and just use whatever exact string I provide?

For example:

            redirect: {
              '../core': 'foo',
              '^../helper-(.*)$': 'foo-helper-$1',
            },

I simply want to replace `import '../core'` with `import 'foo'` in all cases, and replace `import '../helper-something'` with `import 'foo-helper-something'` in all cases. I don't want it to perform any resolution or to access the filesystem at all. Is it possible to configure it like that?

**Comment by Velenir** [comment]
Resolution is necessary so that it is possible to swap in relative paths and at the same time correctly resolve to modules, especially when there are `node_modules` at different depths in the project (e.g. for multi-package repos). It is kind of the point of the plugin to *resolve* to a different path.

If all you need is to rename the path, your use case may be better served by [transform-rename-import](https://www.npmjs.com/package/babel-plugin-transform-rename-import), [import-export-rename](https://www.npmjs.com/package/babel-plugin-import-export-rename) or [import-rename](https://www.npmjs.com/package/babel-plugin-import-rename).
